# Container image that runs your code
FROM ghcr.io/epicgames/unreal-engine:dev-5.2.1 as unreal

# install libglib
RUN apt-get update
RUN apt-get install -y libglib2.0-dev

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY build-plugin.sh /build-plugin.sh

# Adds permissions to execute copied entrypoint.sh
RUN sudo chmod +x /build-plugin.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT /build-plugin.sh

